# Generated by Django 2.0.2 on 2018-02-17 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('T2API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('mac',), 'permissions': (('show_status', 'Can show status vars'), ('register_device', 'Can register a device'), ('change_product', 'Can change associated procduct'))},
        ),
    ]
