# Generated by Django 2.0.2 on 2018-02-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T2API', '0006_auto_20180217_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='deviceUser',
            field=models.BooleanField(default=False),
        ),
    ]
