# Generated by Django 2.0.2 on 2018-02-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T2API', '0007_apiuser_deviceuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
