# Generated by Django 2.0.2 on 2018-02-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T2API', '0009_device_last_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_ping',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.RemoveField(
            model_name='device',
            name='resolution'
        ),
        migrations.AddField(
            model_name='device',
            name='resolution',
            field=models.IntegerField(default=10),
        ),
    ]
