# Generated by Django 2.0.2 on 2018-02-17 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('T2API', '0011_notification_priceoffer_productcategory_producthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='T2API.PriceOffer'),
        ),
    ]
