# Generated by Django 2.0.2 on 2018-02-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T2API', '0012_auto_20180217_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceoffer',
            name='name',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceoffer',
            name='price',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceoffer',
            name='seller',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceoffer',
            name='vat',
            field=models.IntegerField(default=7, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='type',
            field=models.CharField(default='primary', max_length=25),
        ),
    ]
